services:
  - type: web
    name: web-e-absensi-qr
    env: php
    plan: free
    region: oregon
    branch: master
    buildCommand: composer install --prefer-dist --no-interaction && php -r "file_exists('.env') || copy('.env.example', '.env');" && php artisan key:generate --force && php -r "file_exists('database/database.sqlite') || touch('database/database.sqlite');" && php artisan migrate --force && php artisan storage:link
    startCommand: php artisan serve --host=0.0.0.0 --port $PORT
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: 'false'
      - key: APP_URL
        value: 'https://website-smanis.onrender.com'
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: '/var/www/html/database/database.sqlite'
      - key: BROADCAST_DRIVER
        value: log
      - key: CACHE_DRIVER
        value: file
      - key: SESSION_DRIVER
        value: file
      - key: QUEUE_CONNECTION
        value: sync
